### ISSUE TITLE
Version 8.0.0.4

### ISSUE THREAD

**Issue by tfhartmann** [smarmie/puppet-networker#2]
Any Idea if there are problems on networker 8.0.0.4 ?

**Comment by smarmie** [comment]
There shouldn't be; IMHO, it should work with any 8.0.x.x version, but I didn't have the chance to test it yet.
I have plans to do some more tests in February.

**Comment by tfhartmann** [comment]
I'll give it a whirl and let you know what I find!

**Comment by tfhartmann** [comment]
So far seems to work like buttah

**Comment by smarmie** [comment]
Good to know. Could you tell me what distro/arch are you using? Also, are you installing from a yum repo or from satellite/spacewalk? Do you think the module should also manage the install source? What would you like to see in the module?
Thanks.

**Comment by tfhartmann** [comment]
So far I've tested on x86_64 RHEL5 and 6, and I've been placing the RPM's in a local yum repo. So far it's been pretty smooth, had a couple of issues with upgrade on rhel5, but a uninstall/reinstall seems to work. Maybe a purge param so that you can purge networker completely and start over? We are going from networker 7.x.x -> 8.x.x so doing a big-ish upgrade of all the clients.
